# Generated by Django 4.2.2 on 2023-06-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sciName",
                    models.CharField(max_length=75, verbose_name="nom scientifique"),
                ),
                (
                    "comNameFr",
                    models.CharField(max_length=75, verbose_name="nom français"),
                ),
                (
                    "comNameEs",
                    models.CharField(max_length=75, verbose_name="nom espagnol"),
                ),
                (
                    "comNameEn",
                    models.CharField(max_length=75, verbose_name="nom anglais"),
                ),
                (
                    "speciesCode",
                    models.CharField(max_length=75, verbose_name="code d'espèce"),
                ),
                ("category", models.CharField(max_length=75, verbose_name="catégorie")),
                ("taxonOrder", models.CharField(max_length=75, verbose_name="taxon")),
                (
                    "bandingCodes",
                    models.CharField(max_length=75, verbose_name="banding codes"),
                ),
                (
                    "comNameCodes",
                    models.CharField(max_length=75, verbose_name="code commun"),
                ),
                (
                    "sciNameCodes",
                    models.CharField(max_length=75, verbose_name="code scientifique"),
                ),
                ("order", models.CharField(max_length=75, verbose_name="ordre")),
                (
                    "familyCode",
                    models.CharField(max_length=75, verbose_name="code de famille"),
                ),
                (
                    "familyComName",
                    models.CharField(
                        max_length=75, verbose_name="nom de famille commun"
                    ),
                ),
                (
                    "familySciName",
                    models.CharField(
                        max_length=75, verbose_name="nom de famille scientifique"
                    ),
                ),
                ("reportAs", models.CharField(max_length=75, verbose_name="")),
                ("extinct", models.CharField(max_length=75, verbose_name="")),
                ("extinctYear", models.CharField(max_length=75, verbose_name="")),
            ],
        ),
    ]
