# Generated by Django 4.2.2 on 2023-06-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geographie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipalite",
            name="code",
            field=models.CharField(
                default="CA-QC-OU",
                max_length=8,
                verbose_name="Code de MRC",
            ),
            preserve_default=False,
        ),
    ]
