# Generated by Django 4.2.2 on 2023-06-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geographie", "0003_alter_municipalite_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="municipalite",
            name="code",
        ),
        migrations.AddField(
            model_name="mrc",
            name="code",
            field=models.CharField(
                default="CA-QC-OU", max_length=8, verbose_name="Code de MRC"
            ),
            preserve_default=False,
        ),
    ]
