# Generated by Django 4.2.2 on 2023-06-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(max_length=75, verbose_name="Nom du site"),
                ),
                (
                    "loc_id",
                    models.CharField(max_length=10, verbose_name="Id de localisation"),
                ),
            ],
        ),
    ]
